#!/bin/bash

"${PTXDIST_ICECC_CREATE_ENV_REAL}" "${@}" --compression none || exit

ptxd_get_path *.tar*
env="${ptxd_reply}"
mkdir tmp
cd tmp
tar xf "../${env}"

find -type f | xargs strip

tar -ch --numeric-owner -zvf "../${env//.*}.tar.gz" *

cd ..
rm -rf tmp
if [ "${env}" != "${env//.*}.tar.gz" ]; then
	rm "${env}"
fi
